-- Account-free child profiles are household records, never authentication identities.
create table child_profiles (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  color text not null check (color ~ '^#[0-9a-fA-F]{6}$'),
  created_at timestamptz not null default now(),
  unique (household_id, id)
);
create table child_calendar_links (
  child_id uuid not null references child_profiles(id) on delete cascade,
  calendar_preference_id uuid not null references calendar_preferences(id) on delete cascade,
  primary key (child_id, calendar_preference_id)
);
alter table planning_items add column child_id uuid references child_profiles(id) on delete set null;
create table task_routines (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  created_by uuid not null references users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 1000),
  child_id uuid references child_profiles(id) on delete set null,
  frequency text not null check (frequency in ('daily', 'weekly')),
  interval integer not null check (interval between 1 and 52),
  weekdays integer[] not null default '{}',
  starts_on date not null,
  ends_on date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (ends_on is null or ends_on >= starts_on),
  check (weekdays <@ array[0,1,2,3,4,5,6]),
  unique (household_id, id)
);
alter table planning_items
  add column routine_id uuid references task_routines(id) on delete set null,
  add column routine_occurrence_date date;
-- This ledger survives deletion/movement of an occurrence. NULL item_id is a
-- deliberate deletion tombstone and must never be regenerated by a later read.
create table task_routine_occurrences (
  routine_id uuid not null references task_routines(id) on delete cascade,
  occurrence_date date not null,
  item_id uuid references planning_items(id) on delete set null,
  primary key (routine_id, occurrence_date)
);
create table week_templates (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  created_at timestamptz not null default now()
);
create table week_template_applications (
  template_id uuid not null references week_templates(id) on delete cascade,
  week_start_date date not null check (extract(isodow from week_start_date) = 1),
  applied_by uuid not null references users(id) on delete cascade,
  applied_at timestamptz not null default now(),
  primary key (template_id, week_start_date)
);
create table weekly_reviews (
  household_id uuid not null references households(id) on delete cascade,
  week_start_date date not null check (extract(isodow from week_start_date) = 1),
  priorities text not null default '' check (char_length(priorities) <= 4000),
  meals text not null default '' check (char_length(meals) <= 4000),
  logistics text not null default '' check (char_length(logistics) <= 4000),
  revision integer not null default 0 check (revision >= 0),
  primary key (household_id, week_start_date)
);
create table weekly_review_acknowledgements (
  household_id uuid not null,
  week_start_date date not null,
  user_id uuid not null references users(id) on delete cascade,
  revision integer not null,
  reviewed_at timestamptz not null default now(),
  primary key (household_id, week_start_date, user_id),
  foreign key (household_id, week_start_date) references weekly_reviews(household_id, week_start_date) on delete cascade
);
create index task_routines_household_idx on task_routines(household_id);
create index child_profiles_household_idx on child_profiles(household_id);
create index week_templates_household_idx on week_templates(household_id);
create index planning_items_routine_idx on planning_items(routine_id) where routine_id is not null;
create trigger child_profiles_notify after insert or update or delete on child_profiles
for each row execute function notify_household_change();
create trigger task_routines_notify after insert or update or delete on task_routines
for each row execute function notify_household_change();
create trigger week_templates_notify after insert or update or delete on week_templates
for each row execute function notify_household_change();
create trigger weekly_reviews_notify after insert or update or delete on weekly_reviews
for each row execute function notify_household_change();
create trigger weekly_review_acknowledgements_notify after insert or update or delete on weekly_review_acknowledgements
for each row execute function notify_household_change();
-- Enforce household identity at the storage boundary as well as in actions.
alter table planning_items add constraint planning_items_child_household_fk
  foreign key (household_id, child_id) references child_profiles(household_id, id) on delete set null (child_id);
alter table task_routines add constraint task_routines_child_household_fk
  foreign key (household_id, child_id) references child_profiles(household_id, id) on delete set null (child_id);
alter table planning_items add constraint planning_items_routine_household_fk
  foreign key (household_id, routine_id) references task_routines(household_id, id) on delete set null (routine_id);
create function validate_child_calendar_household() returns trigger as $$
begin
  if not exists (
    select 1 from child_profiles c join calendar_preferences cp on cp.household_id = c.household_id
    where c.id = new.child_id and cp.id = new.calendar_preference_id
  ) then
    raise exception 'Child and calendar must belong to the same household.' using errcode = '23514';
  end if;
  return new;
end;
$$ language plpgsql;
create trigger child_calendar_links_household before insert or update on child_calendar_links
for each row execute function validate_child_calendar_household();
