services:
  common-week:
    environment:
      APPLE_TEAM_ID: ${COMMON_WEEK_APPLE_TEAM_ID:?COMMON_WEEK_APPLE_TEAM_ID is required}
      APPLE_KEY_ID: ${COMMON_WEEK_APPLE_KEY_ID:?COMMON_WEEK_APPLE_KEY_ID is required}
      APPLE_PRIVATE_KEY_BASE64: ${COMMON_WEEK_APPLE_PRIVATE_KEY_BASE64:?COMMON_WEEK_APPLE_PRIVATE_KEY_BASE64 is required}
      APPLE_SERVICE_ID: ${COMMON_WEEK_APPLE_SERVICE_ID:?COMMON_WEEK_APPLE_SERVICE_ID is required}
      APPLE_BUNDLE_ID: ${COMMON_WEEK_APPLE_BUNDLE_ID:?COMMON_WEEK_APPLE_BUNDLE_ID is required}
      RESEND_API_KEY: ${COMMON_WEEK_RESEND_API_KEY:?COMMON_WEEK_RESEND_API_KEY is required}
      INVITATION_EMAIL_FROM: ${COMMON_WEEK_INVITATION_EMAIL_FROM:?COMMON_WEEK_INVITATION_EMAIL_FROM is required}
      NOTIFICATION_EMAIL_FROM: ${COMMON_WEEK_NOTIFICATION_EMAIL_FROM:?COMMON_WEEK_NOTIFICATION_EMAIL_FROM is required}
      APNS_TEAM_ID: ${COMMON_WEEK_APNS_TEAM_ID:?COMMON_WEEK_APNS_TEAM_ID is required}
      APNS_KEY_ID: ${COMMON_WEEK_APNS_KEY_ID:?COMMON_WEEK_APNS_KEY_ID is required}
      APNS_PRIVATE_KEY_BASE64: ${COMMON_WEEK_APNS_PRIVATE_KEY_BASE64:?COMMON_WEEK_APNS_PRIVATE_KEY_BASE64 is required}
      APNS_BUNDLE_ID: ${COMMON_WEEK_APPLE_BUNDLE_ID:?COMMON_WEEK_APPLE_BUNDLE_ID is required}
